name: asl-recognition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  
  # Core scientific computing
  - numpy=1.24.4
  - pandas=2.1.4
  - scipy=1.11.4
  - scikit-learn=1.3.2
  
  # Machine learning frameworks
  - tensorflow=2.15.0
  - keras=2.15.0
  
  # Computer vision
  - opencv=4.8.1
  - pillow=10.1.0
  
  # Visualization
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - plotly=5.17.0
  
  # Jupyter environment
  - jupyter=1.0.0
  - jupyterlab=4.0.9
  - ipykernel=6.27.1
  - ipywidgets=8.1.1
  
  # Development tools
  - pytest=7.4.3
  - black=23.11.0
  - flake8=6.1.0
  
  # System utilities
  - wget=1.21.4
  - curl=8.4.0
  
  # pip dependencies not available in conda
  - pip:
    - mediapipe==0.10.21
    - kaggle==1.5.16
    - albumentations==1.3.1
    - librosa==0.10.1
    - soundfile==0.12.1
    - tqdm==4.66.1
    - python-dotenv==1.0.0
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - websockets==12.0
    - protobuf==4.25.3
    - flatbuffers==23.5.26
    - absl-py==2.0.0